# -*- coding: utf-8 -*-
"""Sucesion_SD.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1qZZVj-7FUZUfdselKutGrWfZ09mtDJ0J
"""

# 1/10^n 
def sucesion(n):
  n = 10
  lista =[]
  for i in range (1,n+1):
    s = '\\frac{1}{10}^'+str(i)+'}'
    lista.append(s)
  print(lista)

#n = int(input("Cual es n:"))
sucesion(n)



$