# -*- coding: utf-8 -*-
"""TrianguloEquilatero.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/11ECe6nKvEqub_aWzZLbsdCdiDt9G-aIz
"""

# Triangulo equilatero
import matplotlib.pyplot as plt

L = 5
x1, y1 = 0, 0
x2, y2 = L, 0
x3, y3 = L/2, (3**0.5)/2*L

fig, ax = plt.subplots()
ax.plot([x1, x2], [y1, y2], color='blue')
ax.plot([x2, x3], [y2, y3], color='blue')
ax.plot([x3, x1], [y3, y1], color='blue')
ax.set_title('Triángulo equilátero de lado L')
ax.set_xlabel('x')
ax.set_ylabel('y')
plt.show()

